name: BuildImage #name of workflow aka github action
on: 
  push: #any git push (change)
    paths:
      - 'Dockerfile' #change to dockerfile
 #   branches:
 #   - master #within master branch

jobs:
  build:
    name: 'Build' #name of job
    runs-on: ubuntu-latest #use github hosted runner - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
