on:
  push:
    branches:
    - master

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "meatsac"
          password: ${{ secrets.PACKAGES_TOKEN }}
          repository: meatsac/alpine-python-selenium-chromium
          tags: latest
