name: running-job #name of workflow aka github action
on: 
  push: #any git push (change)
    paths:
      - 'Dockerfile' #change to dockerfile
jobs:
  simplejob: #name of job
    runs-on: ubuntu-latest #use github hosted runner - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      - name: sample bash output #name of step
        run: echo "Running Job!" #run this command
